name: Java CI and Deploy to AWS EC2 with Docker

on:
  push:
    branches: [ "Week10" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 and Build
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Docker Image
        run: |
          docker build -t your-app:latest .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Decode and save .pem file
        env:
          EC2_SSH_KEY_BASE64: ${{ secrets.EC2_SSH_KEY_BASE64 }}
        run: |
          echo "$EC2_SSH_KEY" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Upload Docker Image to EC2 and Run
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Docker 이미지 저장 후 EC2에 전송
          docker save your-app:latest | bzip2 | ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'bunzip2 | docker load'

          # application-secret.yml 파일을 /app/config에 마운트하여 Docker 컨테이너 실행
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            docker stop your-app-container || true
            docker rm your-app-container || true
            docker run -d --name your-app-container -v /path/on/ec2/application-secret.yml:/app/config/application-secret.yml -p 8080:8080 your-app:latest
          EOF
