name: Java CI and Deploy to AWS EC2 with Docker

on:
  push:
    branches: [ "readme" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 and Build
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Docker Image
        run: |
          docker build -t care-app:latest .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Save SSH key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_SSH_KEY" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Upload Docker Image to EC2 and Run
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Docker 이미지 저장 후 EC2에 전송
          docker save care-app:latest | bzip2 | ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'bunzip2 | docker load'

          # 기존 컨테이너 중지 및 삭제 후 새 컨테이너 실행
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            echo "기존 컨테이너 중지 및 삭제 중..."
            docker stop care-app-container || echo "실행 중인 컨테이너 없음"
            docker rm care-app-container || echo "제거할 컨테이너 없음"
            echo "새로운 컨테이너를 실행합니다."
            docker run -d --name care-app-container -v /path/on/ec2/application-secret.yml:/app/config/application-secret.yml -p 8080:8080 care-app:latest
          EOF
